# Generated by Django 5.0.6 on 2024-06-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='encrypted_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='encrypted_contact_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='encrypted_contact_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='encrypted_duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='encrypted_duties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
